param(
    [string]$InstallDir,
    [string]$BinDir,
    [string]$ConfigDir,
    [string]$DataDir,
    [string]$Binary,
    [switch]$Build,
    [switch]$OverwriteConfig,
    [switch]$NoPathUpdate,
    [switch]$MachineScope,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"
$RootDir = Resolve-Path (Join-Path $PSScriptRoot "..")
$Scope = if ($MachineScope) { "Machine" } else { "User" }

if (-not $InstallDir) {
    if ($MachineScope) {
        $InstallDir = Join-Path ${env:ProgramFiles} "docker-manager"
    } else {
        $InstallDir = Join-Path $env:LOCALAPPDATA "docker-manager"
    }
}
if (-not $BinDir) { $BinDir = Join-Path $InstallDir "bin" }
if (-not $ConfigDir) {
    if ($MachineScope) {
        $ConfigDir = Join-Path $env:ProgramData "docker-manager"
    } else {
        $ConfigDir = Join-Path $env:APPDATA "docker-manager"
    }
}
if (-not $DataDir) { $DataDir = Join-Path $InstallDir "data" }

$LibexecDir = Join-Path $InstallDir "lib"
$ConfigFile = Join-Path $ConfigDir "dm.yaml"
$OutputDir = Join-Path $DataDir "images"
$YamlOutputDir = $OutputDir.Replace("'", "''")
$InstalledBin = Join-Path $LibexecDir "dm-bin.exe"
$Wrapper = Join-Path $BinDir "dm.cmd"
$Manifest = Join-Path $ConfigDir "install.json"

function Invoke-Step {
    param([scriptblock]$Action, [string]$Text)
    if ($DryRun) {
        Write-Host "DRY-RUN: $Text"
    } else {
        & $Action
    }
}

function Resolve-DmBinary {
    if ($Binary) { return (Resolve-Path $Binary).Path }
    $candidate = Join-Path $RootDir "dm.exe"
    if (Test-Path $candidate) { return (Resolve-Path $candidate).Path }
    $candidate = Join-Path $RootDir "bin/windows/dm.exe"
    if (Test-Path $candidate) { return (Resolve-Path $candidate).Path }
    if ($Build) {
        $built = Join-Path $RootDir "bin/install/dm.exe"
        Invoke-Step {
            New-Item -ItemType Directory -Force -Path (Split-Path -Parent $built) | Out-Null
            $version = if ($env:VERSION) { $env:VERSION } else { "dev" }
            $commit = if ($env:COMMIT) { $env:COMMIT } else { (& git -C $RootDir rev-parse --short HEAD 2>$null).Trim() }
            if (-not $commit) { $commit = "unknown" }
            $buildDate = if ($env:BUILD_DATE) { $env:BUILD_DATE } else { (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ") }
            $ldflags = "-s -w -X docker-manager/internal/version.version=$version -X docker-manager/internal/version.commit=$commit -X docker-manager/internal/version.buildDate=$buildDate"
            Push-Location $RootDir
            try {
                $env:CGO_ENABLED = "0"
                go build -trimpath -ldflags $ldflags -o $built .
            } finally {
                Pop-Location
            }
        } "build $built"
        return $built
    }
    throw "No dm binary found. Pass -Binary PATH or -Build."
}

$SourceBin = Resolve-DmBinary

Write-Host "Installing docker-manager"
Write-Host "  wrapper: $Wrapper"
Write-Host "  binary:  $InstalledBin"
Write-Host "  config:  $ConfigFile"
Write-Host "  data:    $DataDir"

Invoke-Step {
    New-Item -ItemType Directory -Force -Path $BinDir, $LibexecDir, $ConfigDir, $OutputDir | Out-Null
    Copy-Item -Force $SourceBin $InstalledBin
} "create directories and copy binary"

$WrapperContent = @"
@echo off
setlocal EnableExtensions
if "%DM_CONFIG%"=="" set "DM_CONFIG=$ConfigFile"
set "HAS_CONFIG="
for %%A in (%*) do (
  if "%%~A"=="--config" set "HAS_CONFIG=1"
  echo %%~A | findstr /b /c:"--config=" >nul && set "HAS_CONFIG=1"
)
endlocal & if "%HAS_CONFIG%"=="1" ("$InstalledBin" %*) else ("$InstalledBin" --config "%DM_CONFIG%" %*)
"@

Invoke-Step {
    Set-Content -Path $Wrapper -Value $WrapperContent -Encoding ASCII
} "write $Wrapper"

if ($OverwriteConfig -or -not (Test-Path $ConfigFile)) {
    $configText = @"
# docker-manager config generated by install.ps1
proxy:
os: linux
arch: amd64
output_dir: '$YamlOutputDir'
verbose: false
quiet: false
log_json: false
"@
    Invoke-Step {
        Set-Content -Path $ConfigFile -Value $configText -Encoding UTF8
    } "write $ConfigFile"
} else {
    Write-Host "Keeping existing config: $ConfigFile"
}

$manifestData = [ordered]@{
    install_dir = $InstallDir
    bin_dir = $BinDir
    libexec_dir = $LibexecDir
    config_dir = $ConfigDir
    config_file = $ConfigFile
    data_dir = $DataDir
    output_dir = $OutputDir
    scope = $Scope
}
Invoke-Step {
    $manifestData | ConvertTo-Json | Set-Content -Path $Manifest -Encoding UTF8
} "write $Manifest"

Invoke-Step {
    [Environment]::SetEnvironmentVariable("DM_HOME", $DataDir, $Scope)
    [Environment]::SetEnvironmentVariable("DM_CONFIG", $ConfigFile, $Scope)
    [Environment]::SetEnvironmentVariable("DM_OUTPUT_DIR", $OutputDir, $Scope)
    if (-not $NoPathUpdate) {
        $oldPath = [Environment]::GetEnvironmentVariable("PATH", $Scope)
        $parts = @()
        if ($oldPath) { $parts = $oldPath -split ';' }
        if ($parts -notcontains $BinDir) {
            $newPath = if ($oldPath) { "$BinDir;$oldPath" } else { $BinDir }
            [Environment]::SetEnvironmentVariable("PATH", $newPath, $Scope)
        }
    }
} "set environment variables"

Write-Host "Installation complete."
Write-Host "Restart the terminal, then run: dm version"
